{{- range .Values.applications }}
# Application {{.name | lower}}
{{- if or ( not .disable) ( eq .disable false) }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$.Values.beamline}}-{{.name | lower}}-application
  namespace: {{ .Values.argocdNamespace | default "argocd" }}
  labels:
    rootapp: {{ $.Chart.Name }}
    rootappver: {{ $.Chart.Version }}
    beamline: {{ $.Values.beamline | quote }}
    revision: {{$.Values.targetRevision}}
    type: "application"

    {{- if and .gitRepoApp .gitRepoApp.branch}}
    apprevison: "{{.gitRepoApp.branch}}"
    {{- end }}
    {{- if and .gitRepoConfig .gitRepoConfig.url .gitRepoConfig.branch }}
    configrevison: "{{.gitRepoConfig.branch}}"
    {{- end }}
    application: {{.name | lower}}

spec:
  project: {{ $.Values.argocdProject | default "default" }}
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/generic-application-chart.git'
    path: .
    targetRevision:  {{ $.Values.targetRevision }}
    helm:
      releaseName: {{ .name | lower }}
      values: |
          http_proxy: {{ $.Values.http_proxy | quote }}
          https_proxy: {{ $.Values.https_proxy | quote }}
          no_proxy: {{ $.Values.no_proxy | quote }}

          {{- toYaml . | nindent 10 }}
          beamline: {{ $.Values.beamline | quote }}
          {{- if $.Values.epicsConfiguration.name }}
          epicsConfiguration:
            name: {{ $.Values.epicsConfiguration.name | quote}}
            gateway: gateway.{{ $.Values.namespace }}.svc
          {{- end }}
          
          {{- if and $.Values.baseIp .staticIp }}
          staticIP: {{ include "allocateIpFromName" (dict "name" .name "namespace" $.Values.namespace "baseIp" $.Values.baseIp "startIp" $.Values.startIp) }}

          {{- end }}

          {{- if and (not $.Values.gitRepoConfig) (or .gitinit .gitpath)}}
          gitRepoConfig:
            url: {{$.Values.giturl}}
            {{- if .gitpath }}
            path: config/applications/{{.gitpath}}
            {{- else }}
            path: config/applications/{{.name}}
            {{- end }}
            {{- if .gitrev }}
            branch: {{.gitrev}}
            {{- else }}
            branch: {{$.Values.gitrev}}
            {{- end }}
            {{- if .token }}
            token: {{.token}}
            {{- else }}
            token: {{$.Values.token}}
            {{- end }}
          {{- end }}
          {{- if not .resources }}
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          {{- end }}
          {{- if $.Values.serviceAccountName }}
          serviceAccount:
            create: false
            annotations: {}
            name: {{$.Values.serviceAccountName}}
          {{- end }}


      
  destination:
    server: 'https://kubernetes.default.svc'
    {{- if .namespace }}
    namespace: {{ .namespace | quote }}
    {{- else }}
    ## main deploy namespace
    namespace: {{ $.Values.namespace | quote }}

    {{- end}}
  syncPolicy:
    {{- toYaml $.Values.syncPolicy | nindent 10 }}
  info: 
  {{- if .info }}
    - name: message
      value: "{{ .info }}"
  {{- end }}
  {{- if .asset }}
    - name: asset
      value: "{{ .asset }}"
  {{- end }}
## END {{.name | lower}}
{{- else }}
## not deplyed {{ .name | lower }}
{{- end }}
---
{{- end }}
