{{- if .Values.applications }}
{{- range .Values.applications }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.name}}"
  namespace: argocd
  labels:
    rootapp: {{ $.Chart.Name }}
    rootappver: {{ $.Chart.Version }}
    beamline: {{ $.Values.beamline | quote }}
    revision: {{$.Values.targetRevision}}
    {{- if .gitRepoApp.url }}
    apprevison: "{{.gitRepoApp.branch}}"
    {{- end }}
    {{- if .gitRepoConfig.url }}
    configrevison: "{{.gitRepoConfig.branch}}"
    {{- end }}
    application: {{.name}}

spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/generic-application-chart.git'
    path: .
    targetRevision:  {{ $.Values.targetRevision }}
    helm:
      values: |
          {{- toYaml . | nindent 12 }}


      
  destination:
    server: 'https://kubernetes.default.svc'
    {{- if .namespace }}
    namespace: {{ .namespace | quote }}
    {{- else }}
    ## main deploy namespace
    namespace: {{ $.Values.namespace | quote }}

    {{- end}}
  syncPolicy:
    {{- toYaml $.Values.syncPolicy | nindent 10 }}
{{- end }}
{{- end }}
