{{- range .Values.applications }}
# Application {{.name}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$.Values.beamline}}-{{.name}}-application
  namespace: argocd
  labels:
    rootapp: {{ $.Chart.Name }}
    rootappver: {{ $.Chart.Version }}
    beamline: {{ $.Values.beamline | quote }}
    revision: {{$.Values.targetRevision}}
    {{- if .gitRepoApp.url }}
    apprevison: "{{.gitRepoApp.branch}}"
    {{- end }}
    {{- if and .gitRepoConfig and $.Values.gitRepoConfig.url  }}
    configrevison: "{{.gitRepoConfig.branch}}"
    {{- end }}
    application: {{.name}}

spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/generic-application-chart.git'
    path: .
    targetRevision:  {{ $.Values.targetRevision }}
    helm:
      releaseName: {{ .name }}
      values: |
          {{- toYaml . | nindent 10 }}
          {{- if and (not $.Values.gitRepoConfig) (or .gitinit .gitpath)}}
          gitRepoConfig:
            url: {{$.Values.giturl}}
            {{- if .gitpath }}
            path: .gitpath
            {{- else }}
            path: config/services/{{.name}}
            {{- end }}
            {{- if .gitrev }}
            branch: {{.gitrev}}
            {{- else }}
            branch: {{$.Values.gitrev}}
            {{- end }}
            {{- if .exec }}
            exec: {{.exec}}
            {{- end }} 
          {{- end }}
          {{- if not .resources }}
          resources:
            limits:
              cpu: 1
              memory: 2Gi
          {{- end }}
          {{- if $.Values.serviceAccountName }}
          serviceAccount:
            create: false
            annotations: {}
            name: {{$.Values.serviceAccountName}}
          {{- end }}


      
  destination:
    server: 'https://kubernetes.default.svc'
    {{- if .namespace }}
    namespace: {{ .namespace | quote }}
    {{- else }}
    ## main deploy namespace
    namespace: {{ $.Values.namespace | quote }}

    {{- end}}
  syncPolicy:
    {{- toYaml $.Values.syncPolicy | nindent 10 }}

## END {{.name}}
---
{{- end }}
