{{- range .Values.applications }}
# Application {{.name}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$.Values.beamline}}-{{.name}}-application
  namespace: argocd
  labels:
    rootapp: {{ $.Chart.Name }}
    rootappver: {{ $.Chart.Version }}
    beamline: {{ $.Values.beamline | quote }}
    revision: {{$.Values.targetRevision}}
    {{- if and .gitRepoApp .gitRepoApp.branch}}
    apprevison: "{{.gitRepoApp.branch}}"
    {{- end }}
    {{- if and .gitRepoConfig and $.gitRepoConfig.url  }}
    configrevison: "{{.gitRepoConfig.branch}}"
    {{- end }}
    application: {{.name}}

spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/generic-application-chart.git'
    path: .
    targetRevision:  {{ $.Values.targetRevision }}
    helm:
      releaseName: {{ .name }}
      values: |
          {{- toYaml . | nindent 10 }}
          beamline: {{ $.Values.beamline | quote }}
          {{- if $.Values.epicsConfiguration.name }}
          epicsConfiguration:
            name: {{ $.Values.epicsConfiguration.name | quote}}
            gateway: {{ $.Values.epicsConfiguration.services.gateway.name }}.{{ $.Values.namespace }}
          {{- end }}
          {{- if and (not $.Values.gitRepoConfig) (or .gitinit .gitpath)}}
          gitRepoConfig:
            url: {{$.Values.giturl}}
            {{- if .gitpath }}
            path: .gitpath
            {{- else }}
            path: config/applications/{{.name}}
            {{- end }}
            {{- if .gitrev }}
            branch: {{.gitrev}}
            {{- else }}
            branch: {{$.Values.gitrev}}
            {{- end }}
          {{- end }}
          {{- if not .resources }}
          resources:
            limits:
              cpu: 1
              memory: 2Gi
          {{- end }}
          {{- if $.Values.serviceAccountName }}
          serviceAccount:
            create: false
            annotations: {}
            name: {{$.Values.serviceAccountName}}
          {{- end }}


      
  destination:
    server: 'https://kubernetes.default.svc'
    {{- if .namespace }}
    namespace: {{ .namespace | quote }}
    {{- else }}
    ## main deploy namespace
    namespace: {{ $.Values.namespace | quote }}

    {{- end}}
  syncPolicy:
    {{- toYaml $.Values.syncPolicy | nindent 10 }}
  {{- if .info }}
  info: 
    message: |
        {{ .info }}
  {{- end }}
## END {{.name}}
---
{{- end }}
