{{- if .Values.epicsConfiguration.services.archiver.name }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.beamline }}-{{.Values.epicsConfiguration.services.archiver.name }}"
  namespace: argocd
  labels:
    rootapp: {{ .Chart.Name }}
    rootappver: {{ .Chart.Version }}
    beamline: {{ .Values.beamline | quote }}
    revision: {{.Values.targetRevision}}
spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/epics-archiver-chart.git'
    path: .
    targetRevision: {{.Values.targetRevision}}
    helm:
      values: |
          beamline: {{ .Values.beamline | quote }}
          serviceAccountName: {{.Values.serviceAccountName }}
          {{- if .Values.epicsConfiguration.services.archiver.securityContext }}
          securityContext:
            {{- toYaml .Values.epicsConfiguration.services.archiver.securityContext | nindent 12 }}
          {{- else }}
          securityContext:
            {{- if .Values.openshift }}
            privileged: true
            {{- end }}
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          {{- end}}
          epicsConfiguration:
            name: {{ .Values.epicsConfiguration.name | quote}}
            gateway: '{{- include "gateway-service" . }}' ## override with gateway
          {{- if .Values.epicsConfiguration.services.archiver.dataVolume }}
          dataVolume:
              {{- toYaml .Values.epicsConfiguration.services.archiver.dataVolume | nindent 12 }}
          {{- else }}
          dataVolume:
            claim:  ## an existing claim or empty will create a new one
            size: 21Gi ## size of the claim
            accessMode: ReadWriteOnce
          {{- end }}

          mysql:
            host: '{{- include "mysql-service" . }}'
            dbname: arcappl
            user: arcappl
            pass: arcappl
          ingress:
            enabled: true
            className: {{.Values.ingressClassName}}

            hosts:
              - host: '{{- include "archiver-url" . }}'
                paths:
                  - path: /
                    pathType: prefix
    
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 10 }}
{{- end }}