{{- if .Values.epicsConfiguration.services.gateway.name }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.beamline }}-{{.Values.epicsConfiguration.services.gateway.name}}"
  namespace: argocd
  labels:
    rootapp: {{ .Chart.Name }}
    rootappver: {{ .Chart.Version }}
    beamline: {{ .Values.beamline | quote }}
    revision: {{.Values.targetRevision}}

spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/ca-gateway-chart.git'
    path: .
    targetRevision:  {{.Values.targetRevision}}
    helm:
      values: |
          beamline: {{ .Values.beamline | quote }}
          replicaCount: {{ .Values.epicsConfiguration.services.gateway.replica }}  
          epicsConfiguration:
            name: {{ .Values.epicsConfiguration.name | quote}}
          ingress:
            enabled: false
          
          gitRepoConfig: 
            {{- toYaml .Values.epicsConfiguration.services.gateway.gitRepoConfig | nindent 12 }}
          {{- if .Values.epicsConfiguration.services.gateway.ip }}
          service:
            type: "LoadBalancer"
            loadBalancerIP: {{ .Values.epicsConfiguration.services.gateway.ip }}
          {{- end}}
      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
{{- end }}