{{- if .Values.epicsConfiguration.cagateway -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.beamline }}-{{.Values.epicsConfiguration.gateway}}"
  namespace: argocd
  labels:
    rootapp: {{ .Chart.Name }}
    rootappver: {{ .Chart.Version }}
    beamline: {{ .Values.beamline | quote }}
    revision: {{.Values.targetRevision}}

spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/ca-gateway-chart.git'
    path: .
    targetRevision:  {{.Values.targetRevision}}
    helm:
      values: |
          beamline: {{ .Values.beamline | quote }}
          replicaCount: {{ .Values.gatewayReplica }}  
          epicsConfiguration:
            name: {{ .Values.epicsConfiguration.name | quote}}
          ingress:
            enabled: false
          gitRepoConfig:
            url: https://baltig.infn.it/lnf-da-control/sparc-k8s-ecs.git
            path: config/services/ca-gateway
            branch: main
            exec: start.sh
          service:
            type: "LoadBalancer"
            loadBalancerIP: {{ .Values.gatewaybalancer }}
      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
{{- end }}