{{- if .Values.epicsConfiguration.services.channelfinder.name }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.beamline}}-{{ .Values.epicsConfiguration.services.channelfinder.name }}"
  namespace: argocd
  labels:
    rootapp: {{ .Chart.Name }}
    rootappver: {{ .Chart.Version }}
    beamline: {{ .Values.beamline | quote }}
        revision: {{.Values.targetRevision}}

spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/channelfinder-chart.git'
    path: .
    targetRevision:  {{.Values.targetRevision}}
    helm:
      values: |
          beamline: {{ .Values.beamline | quote }}
          replicaCount: {{ .ValuesepicsConfiguration.services.channelfinder.replica }}  
          epicsConfiguration:
            name: {{ .Values.epicsConfiguration.name | quote}}
            gateway: '{{- include "gateway-service" . }}' ## override with gateway
          elasticsearch:
            network:
              host: {{ .Values.backend.elasticsearch.host}}.{{ .Values.backend.namespace}}.svc.cluster.local
          aa:
            urls: "{'default': 'http://{{- include "archiver-url" . -}}:17665'}"
            enabled: true
            pva: true

          ingress:
            enabled: true
            hosts:
              - host: '{{- include "channelfinder-url" . }}'
                paths:
                  - path: /
                    pathType: ImplementationSpecific
                    port: 80
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
{{- end -}}