{{- if .Values.epicsConfiguration.services.console.name }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.beamline }}-{{ .Values.epicsConfiguration.services.console.name }}"
  namespace: argocd
  labels:
    rootapp: {{ .Chart.Name }}
    rootappver: {{ .Chart.Version }}
    beamline: {{ .Values.beamline | quote }}
    revision: {{.Values.targetRevision}}

spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/epics-console-chart.git'
    path: .
    targetRevision: {{.Values.targetRevision}}
    helm:
      values: |
          beamline: {{ .Values.beamline | quote }}
          replicaCount: {{ .Values.epicsConfiguration.services.console.replica }}
          serviceAccountName: {{.Values.serviceAccountName }}
          {{- if .Values.epicsConfiguration.services.console.securityContext }}
          securityContext:
            {{- toYaml .Values.epicsConfiguration.services.console.securityContext | nindent 12 }}
          {{- else }}
          securityContext:
            {{- if .Values.openshift }}
            privileged: true
            {{- end }}
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          {{- end}}

          epicsConfiguration:
            name: {{ .Values.epicsConfiguration.name | quote}}
            gateway: '{{- include "gateway-service" . }}' ## override with gateway
    
          ingress:
            enabled: true
            hosts:
              - host: '{{- include "console-url" . }}'
                paths:
                  - path: /
                    pathType: ImplementationSpecific
          opi:
            {{- toYaml .Values.epicsConfiguration.services.console.gitRepoConfig | nindent 12 }}
    
        
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 10 }}
{{- end -}}