apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.epicsConfiguration.name }}
  labels:
    beamline: {{ .Values.beamline }}
    revision:  {{.Values.targetRevision}}
data:
  EPICS_CA_ADDR_LIST: "{{ .Values.epicsConfiguration.address_list }} {{ include "iocnames" . }}"
  
  EPICS_CA_AUTO_ADDR_LIST: "NO"
  {{- if .Values.epicsConfiguration.conn_tmo}}
  EPICS_CA_CONN_TMO: "{{.Values.epicsConfiguration.conn_tmo}}"
  {{- end }}
  EPICS_CA_MAX_ARRAY_BYTES: "{{ .Values.epicsConfiguration.max_array_bytes }}"
  {{- if .Values.epicsConfiguration.services.gateway }}
  EPICS_CAS_AUTO_BEACON_ADDR_LIST: "NO"
  EPICS_GATEWAY: "{{- include "gateway-service" . }}"
  EPICS_CAS_BEACON_ADDR_LIST: "{{- include "gateway-service" . }}"

  {{- end }}
  {{- if .Values.epicsConfiguration.services.archiver }}
  EPICS_ARCHIVER: '{{- include "archiver-url" . }}'
  {{- end }}
  {{- if .Values.epicsConfiguration.services.channelfinder }}
  CHANNEL_FINDER: '{{- include "channelfinder-url" . }}'
  {{- end}}
  {{- if .Values.epicsConfiguration.services.saveandrestore }}
  PHOEBUS_SAVE_AND_RESTORE: '{{- include "saveandrestore-url" . }}'
  {{- end}}
  {{- if .Values.epicsConfiguration.services.scanserver }}
  PHOEBUS_SCAN_SERVER: '{{- include "scanserver-url" . }}'
  {{- end}}
  {{- if .Values.epicsConfiguration.services.olog }}
  PHOEBUS_OLOG: '{{- include "olog-url" . }}'
  {{- end}}
  {{- if .Values.epicsConfiguration.services.jupyter }}
  # JUPYTER: 'http://{{- include "jupyter-url" . }}'
  {{- end}}
  {{- if .Values.epicsConfiguration.services.console }}
  CONSOLE: 'http://{{- include "console-url" . }}'
  
  {{ .Values.beamline }}-configuration.yaml: |
    epicsConfiguration:
    {{- toYaml .Values.epicsConfiguration | nindent 8 }}
  
  {{ .Values.beamline }}-backend.yaml: |
    epicsConfiguration:
    {{- toYaml .Values.backend | nindent 8 }}
    
  phoebus_settings.ini: |
    
    {{- if .Values.epicsConfiguration.services.gateway }}
    org.phoebus.pv.ca/addr_list={{- include "gateway-service" . }} ## balancer {{.Values.gatewaybalancer}}
    org.phoebus.pv.ca/auto_addr_list=false
    {{- else if .Values.epicsConfiguration.address_list }}
    org.phoebus.pv.ca/addr_list={{ .Values.epicsConfiguration.address_list }}
    org.phoebus.pv.ca/auto_addr_list=false
    {{- else }}
      org.phoebus.pv.ca/auto_addr_list=true
    {{- end }}
    {{- if .Values.epicsConfiguration.services.archiver }}
    org.csstudio.trends.databrowser3/urls=pbraw://{{- include "archiver-url" . }}/retrieval
    org.csstudio.trends.databrowser3/archives=pbraw://{{- include "archiver-url" . }}/retrieval
    {{- end }}

    {{- if .Values.epicsConfiguration.services.olog }}
    org.phoebus.olog.es.api/olog_url=http://{{- include "olog-url" . }}/Olog
    org.phoebus.olog.api/olog_url=http://{{- include "olog-url" . }}/Olog
    org.phoebus.logbook/logbook_factory=olog-es
    org.phoebus.olog.api/username=epics
    org.phoebus.olog.api/password=epics
    {{- end }}
    {{- if .Values.epicsConfiguration.services.channelfinder }}
    org.phoebus.channelfinder/channelfinder.serviceURL=http://{{- include "channelfinder-url" . }}/ChannelFinder
    {{- end}}
    {{- if .Values.epicsConfiguration.services.saveandrestore }}
    org.phoebus.applications.saveandrestore.client/jmasar.service.url=http://{{- include "saveandrestore-url" . }}/save-restore
    {{- end}}
    {{- if .Values.epicsConfiguration.services.scanserver }}
    org.csstudio.scan.client/host=http://{{- include "scanserver-url" . }}
    org.csstudio.scan.client/port=4810
    {{- end}}
    {{- if .Values.epicsConfiguration.services.scanserver }}
    org.csstudio.scan.client/host=http://{{- include "scanserver-url" . }}
    org.csstudio.scan.client/port=4810
    {{- end}}
    {{- if .Values.epicsConfiguration.services.alarmserver }}
    org.phoebus.applications.alarm/server={{.Values.backend.kafka.host}}:{{.Values.backend.kafka.port}}
    org.phoebus.applications.alarm/config_name=Accelerator-{{ .Values.beamline }}
    # org.phoebus.applications.alarm/kafka_properties=
    org.phoebus.applications.alarm/config_names=Accelerator-{{ .Values.beamline }}, Demo
    org.phoebus.applications.alarm/connection_timeout=30
    org.phoebus.applications.alarm/severity_pv_timeout=5
    org.phoebus.applications.alarm/alarm_area_level=2
    org.phoebus.applications.alarm/alarm_area_column_count=3
    org.phoebus.applications.alarm/alarm_area_gap=5
    org.phoebus.applications.alarm/alarm_area_font_size=15
    org.phoebus.applications.alarm/alarm_menu_max_items=10
    org.phoebus.applications.alarm/alarm_tree_startup_ms=2000
    org.phoebus.applications.alarm/alarm_table_columns=Icon, PV, Description, Alarm Severity, Alarm Status, Alarm Time, Alarm Value, PV Severity, PV Status
    # org.phoebus.applications.alarm/alarm_table_color_legacy_background=true
    # org.phoebus.applications.alarm/alarm_table_max_rows=2500
    # org.phoebus.applications.alarm/command_directory=$(user.home)
    # org.phoebus.applications.alarm/annunciator_threshold=3
    # org.phoebus.applications.alarm/annunciator_retention_count=100
    # org.phoebus.applications.alarm/idle_timeout=10
    # org.phoebus.applications.alarm/automated_email_sender=Alarm Notifier <alarm_server@example.org>
    # org.phoebus.applications.alarm/automated_action_followup=mailto:, cmd:
    # org.phoebus.applications.alarm/heartbeat_pv=Demo:AlarmServerHeartbeat
    # org.phoebus.applications.alarm/heartbeat_pv=
    # org.phoebus.applications.alarm/heartbeat_secs=10
    # org.phoebus.applications.alarm/nag_period=00:15:00
    # org.phoebus.applications.alarm/connection_check_secs=5
    # org.phoebus.applications.alarm/disable_notify_visible=false
    # org.phoebus.applications.alarm/shelving_options=1 hour, 6 hours, 12 hours, 1 day, 7 days, 30 days
    # org.phoebus.applications.alarm/Format: M1=Value1, M2=Value2
    # org.phoebus.applications.alarm/macros=TOP=/home/controls/displays,WEBROOT=http://localhost/controls/displays
    # org.phoebus.applications.alarm/max_block_ms=10000

    {{- end}}

  {{- end}}