{{- range .Values.epicsConfiguration.iocs }}
## IOC  {{$.name}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$.Values.beamline}}-{{.name}}-ioc
  namespace: argocd
  labels:
    rootapp: {{ $.Chart.Name }}
    rootappver: {{ $.Chart.Version }}
    beamline: {{ $.Values.beamline | quote }}
    revision: {{$.Values.targetRevision}}
    iocname: {{.name}}
spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
    path: .
    {{- if .targetRevision }}
    targetRevision: {{.targetRevision}}

    {{- else }}
    targetRevision: {{$.Values.targetRevision}}
    {{- end }}
    helm:
      releaseName: {{ .name }}
      parameters:
        - name: beamline
          value: {{ $.Values.beamline | quote }}
        - name: configCA.existingConfigMap
          value: {{ $.Values.epicsConfiguration.name | quote }}

      values: |
          {{- toYaml . | nindent 10 }}
          {{- if and (not $.Values.gitRepoConfig) (or .gitinit .gitpath)}}
          gitRepoConfig:
            url: {{$.Values.giturl}}
            {{- if .gitpath }}
            path: .gitpath
            {{- else }}
            path: config/iocs/{{.name}}
            {{- end }}
            {{- if .gitrev }}
            branch: {{.gitrev}}
            {{- else }}
            branch: {{$.Values.gitrev}}
            {{- end }}
            {{- if .exec }}
            exec: {{.exec}}
            {{- end }} 
          {{- end }}
          {{- if not .resources }}
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
          {{- end }}
          {{- if $.Values.serviceAccountName }}
          serviceAccount:
            create: false
            annotations: {}
            name: {{$.Values.serviceAccountName}}
          {{- end }}

    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ $.Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true

## END  {{$.name}}
---
{{- end }}