{{- range .Values.epicsConfiguration.iocs }}
{{- $ioc := . }}
{{- if $.Values.iocDefaults }}
  {{- $tmpl := .template | default .devtype | default "" }}
  {{- if and $tmpl (hasKey $.Values.iocDefaults $tmpl) }}
    {{- $ioc = mustMergeOverwrite (deepCopy (index $.Values.iocDefaults $tmpl)) . }}
  {{- end }}
{{- end }}
## IOC  {{$ioc.name | lower }}
{{- if or ( not $ioc.disable) ( eq $ioc.disable false) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$.Values.beamline}}-{{$ioc.name | lower}}-ioc
  {{- if $.Values.argocdNamespace }}
  namespace: {{ $.Values.argocdNamespace }}
  {{- else }}
  namespace: argocd
  {{- end }}
  labels:
    rootapp: {{ $.Chart.Name }}
    rootappver: {{ $.Chart.Version }}
    beamline: {{ $.Values.beamline | quote }}
    revision: {{$.Values.targetRevision}}
    iocname: {{$ioc.name | lower}}
    type: "ioc"
    {{- if $ioc.host }}
    iochost: {{$ioc.host}}
    {{- end }}
    {{- if $ioc.devtype }}
    devtype: {{$ioc.devtype}}
    {{- else }}
    devtype: "{{ $ioc.iocdir }}"
    {{- end }}
    {{- if $ioc.devgroup }}
    devgroup: "{{ $ioc.devgroup }}"
    {{- end }}
    {{- if $ioc.template }}
    template: "{{ $ioc.template }}"
    {{- end }}
    
spec:
  project: {{ $.Values.argocdProject | default "default" }}
  source:
    repoURL: {{$ioc.charturl | default $.Values.iocs.charturl}}
    path: .
    {{- if $ioc.targetRevision }}
    targetRevision: {{$ioc.targetRevision}}

    {{- else }}
    targetRevision: {{$.Values.targetRevision}}
    {{- end }}
    helm:
      releaseName: {{ $ioc.name | lower }}
      values: |
          {{- toYaml $ioc | nindent 10 }}
          {{- if $ioc.nfsMounts }}
          nfsMounts:
          {{- toYaml $ioc.nfsMounts | nindent 10 }}
          {{- else }}
          {{- if $.Values.nfsMounts }}
          nfsMounts:
          {{- toYaml $.Values.nfsMounts | nindent 10 }}
          {{- end}}
          {{- end}}

          {{- if and $.Values.ioc_version (not $ioc.image) }}
          ioc_version: {{ $.Values.ioc_version }}
          {{- end }}

          beamline: {{ $.Values.beamline | quote }}
          iocname: "{{ $ioc.name | lower }}"
          

          {{- if $.Values.baseIp }}
          staticIP: {{ include "allocateIpFromName" (dict "name" $ioc.name "namespace" $.Values.namespace "baseIp" $.Values.baseIp "startIp" $.Values.startIp) }}
          {{- end }}
          {{- if $.Values.epik8s_secrets}}
          epik8s_secrets: {{$.Values.epik8s_secrets}}
          {{- end }}
          http_proxy: {{ $.Values.http_proxy | quote }}
          https_proxy: {{ $.Values.https_proxy | quote }}
          no_proxy: {{ $.Values.no_proxy | quote }}
          {{- if $ioc.enable_ingress }}
          ingress:
            enabled: true
            {{- if $.Values.ingressClassName }}
            className: {{$.Values.ingressClassName}}
            {{- end }}
            hosts:
              - host: {{ printf "%s-%s.%s" $.Values.beamline ($ioc.name | lower) $.Values.epik8namespace }}
                paths:
                  - path: /
                    pathType: Prefix
          {{- end}}
          
          {{- if $.Values.epicsConfiguration.name }}
          epicsConfiguration:
            name: {{ $.Values.epicsConfiguration.name | quote}}
            {{- if $ioc.usegateway }}
            {{- if $.Values.epicsConfiguration.services.gateway }}
            gateway: {{- include "gateway-service" . }}.{{ $.Values.namespace }}.svc
            {{- end }}
            {{- if $.Values.epicsConfiguration.services.pvagateway }}
            pvagateway: {{- include "pvagateway-service" . }}.{{ $.Values.namespace }}.svc
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if and (not $.Values.gitRepoConfig) (or $ioc.gitinit $ioc.gitpath $ioc.host)}}
          gitRepoConfig:
            url: {{$.Values.giturl}}
            {{- if $ioc.gitpath }}
            path: {{ $ioc.gitpath }}
            {{- else }}
            {{- if $ioc.iocdir }}
            path: config/iocs/{{$ioc.iocdir}}
            {{- else }}
            path: config/iocs/{{$ioc.name}}
            {{- end }}
            {{- end }}
            {{- if $ioc.gitrev }}
            branch: {{$ioc.gitrev}}
            {{- else }}
            branch: {{$.Values.gitrev}}
            {{- end }}
            {{- if $ioc.token }}
            token: {{$ioc.token}}
            {{- else }}
            token: {{$.Values.token}}
            {{- end }}
            {{- if $ioc.exec }}
            exec: {{$ioc.exec}}
            {{- end }} 
          {{- end }}
          {{- if not $ioc.resources }}
          {{- if eq ($ioc.devtype | default "") "development" }}
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 600m
              memory: 700Mi
          {{- else }}

          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          {{- end }}
          {{- end }}

          {{- if $.Values.serviceAccountName }}
          serviceAccount:
            create: false
            annotations: {}
            name: {{$.Values.serviceAccountName}}
          {{- end }}
          {{- if $ioc.host }}
          ssh:
            host: {{$ioc.host}}
            {{- if $ioc.ssh_options}}
            options: {{$ioc.ssh_options}}
            {{- end }}
            {{- if $ioc.user }}
            user: {{$ioc.user}}
            {{- else }}
            user: root
            {{- end }}
            {{- if $ioc.workdir }}
            workdir: {{$ioc.workdir}}
            {{- else }}
            workdir: "workdir-{{$ioc.name}}"
            {{- end }}
            {{- if $ioc.scpoptions }}
            scpoptions: {{$ioc.scpoptions}}
            {{- end }}
            {{- if $ioc.initcmd }}
            initcmd: {{$ioc.initcmd}}
            {{- end }}
          {{- end }}

    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ $.Values.namespace | quote }}
  {{- if $ioc.autosync }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
  {{- end }}
  info:
    {{- if $ioc.iocname }}
    - name: iocname
      value: "{{$ioc.iocname}}"
    {{- else }}
    - name: iocname
      value: "{{$ioc.name | lower}}"
    {{- end}}
    {{- if $ioc.iocprefix }}
    - name: iocprefix
      value: "{{ $ioc.iocprefix }}"
    {{- end }}
    {{- if $ioc.iocroot }}
    - name: iocroot
      value: "{{ $ioc.iocroot }}"
    {{- end }}
    {{- if $ioc.workdir }}
    - name: workdir
      value: "{{$ioc.workdir}}"
    {{- end}}

    {{- if $ioc.asset }}
    - name: asset
      value: "{{ $ioc.asset }}"
    {{- end }}
    {{- if $ioc.info }}
    - name: message
      value: "{{ $ioc.info }}"
    {{- end }}
    
    
## END  {{ $ioc.name | lower}}
{{- else }}
## not deployed {{ $ioc.name | lower }}
{{- end }}

---
{{- end }}