{{- range .Values.epicsConfiguration.iocs }}
## IOC  {{$.name}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$.Values.beamline}}-{{.name}}-ioc
  namespace: argocd
  labels:
    rootapp: {{ $.Chart.Name }}
    rootappver: {{ $.Chart.Version }}
    beamline: {{ $.Values.beamline | quote }}
    revision: {{$.Values.targetRevision}}
    {{- if .iocname }}
    iocname: {{.iocname}}
    {{- else }}
    iocname: {{.name}}
    {{- end}}
    {{- if .host }}
    iochost: {{.host}}
    {{- end }}
    {{- if .workdir }}
    iocdir: {{.workdir}}
    {{- end}}

spec:
  project: default
  source:
    repoURL: {{.charturl}}
    path: .
    {{- if .targetRevision }}
    targetRevision: {{.targetRevision}}

    {{- else }}
    targetRevision: {{$.Values.targetRevision}}
    {{- end }}
    helm:
      releaseName: {{ .name }}
      values: |
          {{- toYaml . | nindent 10 }}
          beamline: {{ $.Values.beamline | quote }}
          {{- if $.Values.epicsConfiguration.name }}
          epicsConfiguration:
            name: {{ $.Values.epicsConfiguration.name | quote}}
            gateway: {{ $.Values.epicsConfiguration.services.gateway.name }}.{{ $.Values.namespace }}
          {{- end }}
          {{- if and (not $.Values.gitRepoConfig) (or .gitinit .gitpath .host)}}
          gitRepoConfig:
            url: {{$.Values.giturl}}
            {{- if .gitpath }}
            path: .gitpath
            {{- else }}
            {{- if .iocname }}
            path: config/iocs/{{.iocname}}
            {{- else }}
            path: config/iocs/{{.name}}
            {{- end }}
            {{- end }}
            {{- if .gitrev }}
            branch: {{.gitrev}}
            {{- else }}
            branch: {{$.Values.gitrev}}
            {{- end }}
            {{- if .exec }}
            exec: {{.exec}}
            {{- end }} 
          {{- end }}
          {{- if not .resources }}
          resources:
            limits:
              cpu: 1
              memory: 2Gi
          {{- end }}
          {{- if $.Values.serviceAccountName }}
          serviceAccount:
            create: false
            annotations: {}
            name: {{$.Values.serviceAccountName}}
          {{- end }}
          {{- if .host }}
          ssh:
            host: {{.host}}
            {{- if .user }}
            user: {{.user}}
            {{- end }}
            {{- if .workdir }}
            workdir: {{.workdir}}
            {{- end }}
          {{- end }}

    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ $.Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
  info:
    {{- if .iocname }}
    - iocname: {{.iocname}}
    {{- else }}
    - iocname: {{.name}}
    {{- end}}
    {{- if .iocprefix }}
    - iocprefix: {{ .iocprefix }}
    {{- end }}
    {{- if .iocroot }}
    - iocroot: {{ .iocroot }}
    {{- end }}
    {{- if .info }}
    - message: |
        {{ .info }}
    {{- end }}
## END  {{$.name}}
---
{{- end }}