{{- range .Values.epicsConfiguration.iocs }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.name}}
  namespace: argocd
  labels:
    rootapp: {{ $.Chart.Name }}
    rootappver: {{ $.Chart.Version }}
    beamline: {{ $.Values.beamline | quote }}
    revision: {{$.Values.targetRevision}}
    iocname: {{.name}}
spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/ioc-chart.git'
    path: .
    {{- if .targetRevision }}
    targetRevision: {{.targetRevision}}

    {{- else }}
    targetRevision: {{$.Values.targetRevision}}
    {{- end }}
    helm:
      parameters:
        - name: beamline
          value: {{ $.Values.beamline | quote }}
        - name: configCA.existingConfigMap
          value: {{ $.Values.epicsConfiguration.name | quote }}

      values: |
          {{- toYaml . | nindent 12 }}
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ $.Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
---
{{- end }}