{{- range .Values.epicsConfiguration.iocs }}
## IOC  {{$.name}}
{{- if or ( not .disable) ( eq .disable false) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{$.Values.beamline}}-{{.name}}-ioc
  namespace: argocd
  labels:
    rootapp: {{ $.Chart.Name }}
    rootappver: {{ $.Chart.Version }}
    beamline: {{ $.Values.beamline | quote }}
    revision: {{$.Values.targetRevision}}
    {{- if .iocname }}
    iocname: {{.iocname}}
    {{- else }}
    iocname: {{.name}}
    {{- end}}
    {{- if .host }}
    iochost: {{.host}}
    {{- end }}
    
spec:
  project: default
  source:
    repoURL: {{.charturl}}
    path: .
    {{- if .targetRevision }}
    targetRevision: {{.targetRevision}}

    {{- else }}
    targetRevision: {{$.Values.targetRevision}}
    {{- end }}
    helm:
      releaseName: {{ .name }}
      values: |
          {{- toYaml . | nindent 10 }}
          beamline: {{ $.Values.beamline | quote }}
          {{- if and $.Values.epicsConfiguration.name $.epicsConfiguration.staticIp }}
          {{- if $.Values.baseIp }}
          baseIp: {{$.Values.baseIp}}
          startIp: {{$.Values.startIp}}
          ipRange: {{$.Values.ipRange}}
          {{- end }}
          {{- end }}

          {{- if $.Values.epicsConfiguration.name }}
          epicsConfiguration:
            name: {{ $.Values.epicsConfiguration.name | quote}}
            {{- if .usegateway -}}
            gateway: {{ $.Values.epicsConfiguration.services.gateway.name }}.{{ $.Values.namespace }}
            {{- end }}
          {{- end }}
          {{- if and (not $.Values.gitRepoConfig) (or .gitinit .gitpath .host)}}
          gitRepoConfig:
            url: {{$.Values.giturl}}
            {{- if .gitpath }}
            path: {{ .gitpath }}
            {{- else }}
            {{- if .iocname }}
            path: config/iocs/{{.iocname}}
            {{- else }}
            path: config/iocs/{{.name}}
            {{- end }}
            {{- end }}
            {{- if .gitrev }}
            branch: {{.gitrev}}
            {{- else }}
            branch: {{$.Values.gitrev}}
            {{- end }}
            {{- if .exec }}
            exec: {{.exec}}
            {{- end }} 
          {{- end }}
          {{- if not .resources }}
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          {{- end }}
          {{- if $.Values.serviceAccountName }}
          serviceAccount:
            create: false
            annotations: {}
            name: {{$.Values.serviceAccountName}}
          {{- end }}
          {{- if .host }}
          ssh:
            host: {{.host}}
            {{- if .ssh_options}}
            options: {{.ssh_options}}
            {{- end }}
            {{- if .user }}
            user: {{.user}}
            {{- end }}
            {{- if .workdir }}
            workdir: {{.workdir}}
            {{- end }}
            {{- if .scpoptions }}
            scpoptions: {{.scpoptions}}
            {{- end }}
          {{- end }}

    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ $.Values.namespace | quote }}
  {{- if .autosync }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
  {{- end }}
  info:
    {{- if .iocname }}
    - name: iocname
      value: "{{.iocname}}"
    {{- else }}
    - name: iocname
      value: "{{.name}}"
    {{- end}}
    {{- if .iocprefix }}
    - name: iocprefix
      value: "{{ .iocprefix }}"
    {{- end }}
    {{- if .iocroot }}
    - name: iocroot
      value: "{{ .iocroot }}"
    {{- end }}
    {{- if .workdir }}
    - name: workdir
      value: "{{.workdir}}"
    {{- end}}

    {{- if .asset }}
    - name: asset
      value: "{{ .asset }}"
    {{- end }}
    {{- if .info }}
    - name: message
      value: "{{ .info }}"
    {{- end }}
    {{- if .devtype }}
    - name: type
      value: "{{ .devtype }}"
    {{- end }}
    {{- if .devgroup }}
    - name: group
      value: "{{ .devgroup }}"
    {{- end }}
## END  {{ .name}}
{{- else }}
## not deployed {{ .name }}
{{- end }}

---
{{- end }}