{{- if .Values.epicsConfiguration.services.jupyter.name }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.beamline }}-{{ .Values.epicsConfiguration.services.jupyter.name }}"
  namespace: argocd
  labels:
    rootapp: {{ .Chart.Name }}
    rootappver: {{ .Chart.Version }}
    beamline: {{ .Values.beamline | quote }}
    revision: {{.Values.targetRevision}}

spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/jupyter-control-notebook-chart.git'
    path: .
    targetRevision: {{.Values.targetRevision}}
    helm:
      values: |
          beamline: {{ .Values.beamline | quote }}
          replicaCount: {{ .Values.consoleReplica }}
          serviceAccountName: {{.Values.serviceAccountName }}
          {{- if .Values.epicsConfiguration.services.jupyter.securityContext }}
          securityContext:
            {{- toYaml .Values.epicsConfiguration.services.jupyter.securityContext | nindent 12 }}
          {{- else }}
          securityContext:
            privileged: {{ .Values.openshift }}
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          {{- end}}
          epicsConfiguration:
            name: {{ .Values.epicsConfiguration.name | quote}}
            gateway: '{{- include "gateway-service" . }}' ## override with gateway
    
          ingress:
            enabled: true
            hosts:
              - host: '{{- include "jupyter-url" . }}'
                paths:
                  - path: /
                    pathType: ImplementationSpecific
                    port: 80
          gitRepoConfig:
            {{- toYaml .Values.epicsConfiguration.services.jupyter.gitRepoConfig | nindent 12 }}
           
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
{{- end }}