{{- if .Values.epicsConfiguration.services.alarmserver.name }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.beamline }}-{{ .Values.epicsConfiguration.services.alarmserver.name }}"
  namespace: argocd
  labels:
    rootapp: {{ .Chart.Name }}
    rootappver: {{ .Chart.Version }}
    beamline: {{ .Values.beamline | quote }}

spec:
  project: default
  source:
    repoURL: 'https://baltig.infn.it/epics-containers/phoebus-services-chart.git'
    path: .
    targetRevision: {{.Values.targetRevision}}
    helm:
      values: |
          beamline: {{ .Values.beamline | quote }}
          replicaCount: {{ .Values.consoleReplica }}
          serviceAccountName: {{.Values.serviceAccountName }}
          {{- if .Values.epicsConfiguration.services.alarmserver.securityContext }}
          securityContext:
            {{- toYaml .Values.epicsConfiguration.services.alarmserver.securityContext | nindent 12 }}
          {{- else }}
          securityContext:
            privileged: {{ .Values.openshift }}
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          {{- end}}

          phoebusservice: "alarmserver"
          epicsConfiguration:
            name: {{ .Values.epicsConfiguration.name | quote}}
            gateway: '{{- include "gateway-service" . }}' ## override with gateway
          kafka:
            host: {{ .Values.backend.kafka.host}}.{{ .Values.backend.namespace}}.svc.cluster.local
            port: {{ .Values.backend.kafka.port}}
          ingress:
            enabled: true
            hosts:
              - host: '{{- include "alarmserver-url" . }}'
                paths:
                  - path: /
                    pathType: ImplementationSpecific
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.namespace | quote }}
  syncPolicy:
    automated:
      prune: true  # Optional: Automatically remove resources not specified in Helm chart
      selfHeal: true
{{- end }}